// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2lMsN14X4uJbzLqHM2EycOQzNW_bs2g8',
    appId: '1:510827504948:web:d43538eb3ec9a3b2c73161',
    messagingSenderId: '510827504948',
    projectId: 'jgh-51441',
    authDomain: 'jgh-51441.firebaseapp.com',
    storageBucket: 'jgh-51441.firebasestorage.app',
    measurementId: 'G-R14DYJ0BR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_eO_9deGzEPC9Rm6iD8eVBO8_mMcEux4',
    appId: '1:510827504948:android:44a8ceb795693aefc73161',
    messagingSenderId: '510827504948',
    projectId: 'jgh-51441',
    storageBucket: 'jgh-51441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO62PMFYd9fbk9HtWnR8ARMMfUEup3NHU',
    appId: '1:510827504948:ios:efa7c85fe53da8efc73161',
    messagingSenderId: '510827504948',
    projectId: 'jgh-51441',
    storageBucket: 'jgh-51441.firebasestorage.app',
    iosBundleId: 'com.example.jghApp',
  );
}
